### ISSUE TITLE
[EPIC] Web3Modal Docs

### ISSUE THREAD

**Issue by crypblizz8** [WalletConnect/web3modal-docs#1]
# Web3 Modal Docs Project

### Overview
This is intended as an overview of critical path work to get to a beta state with the W3M Docs, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

(Moved initial MVP Shipping tasks into a comment below) 

Content Changes
- [x] #7 
- [ ] #8

Design Changes
- Safari Styling
- Mobile Review.
- Nice to have: Better SideBar Collapsing Menu

**Comment by nutty85** [comment]
Update

**Comment by nutty85** [comment]
>

**Comment by nutty85** [comment]
![image](https://user-images.githubusercontent.com/115965595/198386752-4e01d5eb-2643-4efb-b476-abe9b4461e07.png)

**Comment by nutty85** [comment]
[Etherscan.io 27/10/2022 06:35:04] I, hereby verify that I am the owner/creator of the address [0x6B175474E89094C44Da98b954EedeAC495271d0F]

**Comment by nutty85** [comment]
.github/workflows/buddies

**Comment by crypblizz8** [comment]
- Create Docs Page built on Next.js + MDX. 
- Allow users to interact with web3-modal/react components
- Read the guide on what to make.
- MVP Shipping

Deployment

- [x] Staging Deployment
- [x] Production Deployment

Theming
- [x]  Style Guide similar to website
- [x]  Font 
- [x]  Colors

Content
- [x]  Introduction
- [x]  Try it Out
- [x] Get Started
- [x] Guides / React
- [x] Copy Changes Round 1


Main Components
- [x]  Left Side bar (Nesting + Socials)
- [x]  Main Feature CArds
- [x] Video Content
- [x]  Floating TableOfContents(ToC)
- [x]  Try It Out Section 
- [x]  Get Started Section / Template
- [x] Syntax Highlighting
- [x] Mobile Checks 
- [x] Alpha Banner
- [x] Footer Routes

P1
- [x] Home: SVG Flicker
- [x] All: Bold Font is adding another bold font
- [x] All: borderRadius Check
- [x] Home: MetaContent <Head/>
- [x] Home: Feature Cards All Padding 
- [x] Social Button Linking
- [x] TryItOut: Revert Button + New Padding + textVariant
- [x] Home: Tag is now a grey gradient, not pink

P2
- [x] Hover Effect
- [x] TryItOut: Add Icons to 
- [x] SideBar: Docs // text Padding
- [x] SideBar: Font
- [x] - Sidebar: HoverState Grey (Grey9))
- [x] - SideBar: Divider (Grey16)
- [x] - SideBar Hierarchy - Try it Out

HomeVideo
- [x] - Home:Video Video Container
- [x]  - Home:Video1000 Max Width
- [ ]  - Home:VideoGradient Border on Video. 
- [x]  - Home:Video No Controls
- [x]  - Home:Video Video autoplay revist
- [x] - Home: Web3 text <> Button (40px) 3-4em
- [x] Home: Chevron
- [x]  Home: Too large padding: Video and W3M text

Cards
- [x] - Grey24
- [x] - LG: 64 —> 44
- [x] - Networks: Image larger.
- [x] - Interface: 1 px off
- [x] - Margin Bottom and Margin left: not consistent
- [x] - Wallets: Heading4
- [x] - Badge: Powered by WalletConnect Cloud. 
- [x] - T&C: lg
- [x] - Community
- [x]  - Higher padding
- [x]  - Too much padding
- [x] - Community smaller
- [x] - Add Icons
- [x] - Background Colour is different?

TryItOut
- [x] - ICons
- [x] - LowerCase
- [x] - Hover: Brightness
- [x] - Titles: H6
- [x] - T&X is to be SOON
- [x] - LIGHt / DARK Switch

P3
- [x] Clean console logs
- [ ] Double Check ToDos
- [ ] Clean any inline Styling
- [ ] Clean any extra CP Styling

Other
- [x] CloudFlare Data Track
- [ ] i8n

**Comment by chadyj** [comment]
@crypblizz8 can we close this?

**Comment by crypblizz8** [comment]
Worth keeping here to have constant list on what content / PR's need to be updated?

Or we close these issues after each sprint?
